name: uppidi
description: Cross-platform Flutter media uploader with modular provider plugins
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.1
  hive_flutter: ^1.1.0
  dio: ^5.9.2
  flutter_secure_storage: ^10.0.0
  flutter_localizations:
    sdk: flutter
  photo_manager: ^3.9.0
  file_picker: ^8.3.7
  background_downloader: ^9.5.4
  flutter_adaptive_scaffold: ^0.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.14.1
  build_runner: ^2.14.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/l10n/
