name: uppidi_upload
description: Cross-platform Flutter media uploader with modular provider plugins
publish_to: 'none'
version: 1.5.1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.1
  flutter_secure_storage: ^10.2.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  dio: ^5.9.2
  flutter_localizations:
    sdk: flutter
  file_picker: ^12.0.0-0
  receive_sharing_intent: ^1.8.1
  url_launcher: ^6.3.2
  path_provider: ^2.1.0
  open_filex: ^4.6.0
  share_plus: ^13.0.0
  image: ^4.0.0
  pro_image_editor: ^12.4.5
  desktop_drop: ^0.7.1
  pasteboard: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.14.1
  build_runner: ^2.15.0
  flutter_lints: ^6.0.0
  analyzer: ^10.0.1
  flutter_secure_storage_platform_interface: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/l10n/
    - assets/
    - assets/favicons/
    - CHANGELOG.md
